### ISSUE TITLE
failed to install 

### ISSUE THREAD

**Issue by BenEnglundInnovations** [abdalmoniem/AVR4L#14]
Hi,  WHen I try to install this on Ubuntu 14.04.  After everything else is done, then I type "sudo -E ./install.sh"  from folder and I get this:
"You called the script without passing the environment variables, please run as sudo with -E switch"
Any Ideas?   I've been using ubunty for about 4 years, but I would say I'm still a novice at best at using the terminal.  Any help would be great.  Thanks

**Comment by cvam0000** [comment]
have you configure your jdk environment and path correctly , please give a snap of the file /etc/environment
i'm installing AVR4L on my ARCH  for the first time , it was a smooth installation

**Comment by BenEnglundInnovations** [comment]
I'm not sure what I did wrong.  Unfortunately now I'm having troubles with EXCESSIVE inode usage(likely unrelated) So it may be a bit before I get back to trying it again.  Thanks for responding to my calls for help.

**Comment by cvam0000** [comment]
no problem , upgrade your distro and try once more may be not compatible with 14.04

**Comment by BenEnglundInnovations** [comment]
I have since upgraded to 16.04 but have not tried AVR4L again yet.  Im still working on the inode trouble first.  I thought about upgrading to 18.04, but i cannot get Piklab to install on it on another pc.  I currently have Piklab working on 16.04.  I don't want to switch over to AVR from PIC until I have a clear path working under Ubuntu.  Thanks

    On Monday, March 11, 2019, 2:06:14 AM CDT, cvam0000 <notifications@github.com> wrote:  
 
 
no problem , upgrade your distro and try once more may be not compatible with 14.04

**Comment by cvam0000** [comment]
http://photonics.engr.uga.edu/piklab/index.html this might be helpful

**Comment by BenEnglundInnovations** [comment]
That's actually the website I was using as a reference for building the package.  However, I fail more than I succeed at building packages.  Some certain knowledge must be assumed that I do not have.   I did manage to get Piklab working on my other PC with Ubuntu 14.04 then upgraded to 16.04.   That's the one I tried making AVR4L package on.  Thanks for taking the time to find that though.  Now I'm having trouble getting Cura on 18.04.   It installs then tells me it can't find openGL even though I installed Mesa and still no luck.  Also tried a newer Cura from another repository with no luck.  Not having any luck lately.....

    On Tuesday, March 12, 2019, 7:03:00 AM CDT, cvam0000 <notifications@github.com> wrote:  
 
 
http://photonics.engr.uga.edu/piklab/index.html this might be helpful

**Comment by BenEnglundInnovations** [comment]
I tried installing this again, and it worked.   Not sure what I did wrong the first time.
