### ISSUE TITLE
Gtk-Message: Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by ZettaPloom** [abdalmoniem/AVR4L#20]
**Describe the bug**
After clone and install the repository following the steps given, java shows some errors

**To Reproduce**
Follow the steps given at the repository

**Desktop (please complete the following information):**
 - OS: Ubuntu and Parrot security OS

**Comment by OMGdaDPS** [comment]
I have seen that error so many times for different things, it's not even funny anymore lol. To make it quit saying it, all you have to do is install the `canberra-gtk-module` package. 
  The easiest way that I have found to do this, is to open up synaptic package manager (`sudo apt install synaptic` if you don't have it already), and search for `canberra`, and install the relevant packages.
Cheers!
