### ISSUE TITLE
Release will not run on windows 10

### ISSUE THREAD

**Issue by tlf30** [abdalmoniem/AVR4L#6]
The release exe will not run on windows 10.

**Comment by abdalmoniem** [comment]
Sorry for the late reply, can you elaborate more, what is the error and, if you can, attach a screenshot.

**Comment by tlf30** [comment]
See attached, I see that the newer issue is the same. 
![capture](https://user-images.githubusercontent.com/10089434/37227773-3c36fe34-2393-11e8-873f-b882feb96138.PNG)

**Comment by abdalmoniem** [comment]
looks like the tool that I used to make an executable has expired, for the time being, you can run it directly from the .jar file

**Comment by abdalmoniem** [comment]
solved in 262eef8ce9eac06a0c6e4cc7040a5cec83e19fa0
