### ISSUE TITLE
Release not run on windows

### ISSUE THREAD

**Issue by Elektron2016** [abdalmoniem/AVR4L#7]
When you try to start, you receive a message:
This program was made with an Unlicensed compiler. Please buy the PRO version to distribute your EXE.

**Comment by abdalmoniem** [comment]
Please attach a screenshot to further investigate the problem.
FYI, I'm using the Java compiler which is totally free :D

**Comment by Elektron2016** [comment]
![default](https://user-images.githubusercontent.com/17587027/36907999-2279ed28-1e4b-11e8-8d2b-dcb221868054.png)
If run directly .jar file program works. I think problem in AVR4L.exe

**Comment by abdalmoniem** [comment]
well thats a **`workaround`** , for now. I will investigate the problem and find a solution soon ISA.

_Sent from my Galaxy Note4 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by abdalmoniem** [comment]
solved in 262eef8ce9eac06a0c6e4cc7040a5cec83e19fa0
